name: GitHub Pages

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: current

      - name: Build docs
        working-directory: current
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build -c -d build_docs/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create docs update branch
        working-directory: gh-pages
        run: git checkout -b gh-pages/update

      - name: Copy docs
        run: |
          cp -Rf current/build_docs/* gh-pages

      - name: Push docs update branch
        working-directory: gh-pages
        run: |
          git add --all
          git commit -m "Update docs from commit ${{ github.sha }}"
          git push origin gh-pages/update --force

      - name: Open docs update PR
        working-directory: gh-pages
        uses: repo-sync/pull-request@v2
        with:
          source_branch: gh-pages/update
          destination_branch: gh-pages
          pr_title: Update docs from commit ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
