name: GitHub Pages

on:
  push:
    branches:
      - publish
jobs:
  ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: current

      - name: Build docs
        working-directory: current
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build -c -d build_docs/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy docs
        run: |
          cp -Rf current/build_docs/* gh-pages

      - name: Push gh-pages branch
        working-directory: gh-pages
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add --all
          git commit --allow-empty -m "Update docs from commit ${{ github.sha }}"
          git push
