on:
  push:
    branches:
      - publish
jobs:
  dist:
    name: Publish
    runs-on: ubuntu-20.04
    environment: publish
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install --user --upgrade build twine
      - run: python3 -m build
      - run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
